import { Geist, Geist_Mono } from "next/font/google";
import {NetworkTracking} from '@/components/networkTracking'
import { Navbar } from "@/components/navbar";

import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
    <html className="h-full" lang="en">
      <body
        className={` antialiased h-full`}
      >
         <Navbar />
        {children}
       
      </body>
    </html>
    </ClerkProvider>
  );
}
