import { Geist, Geist_Mono } from "next/font/google";
import { NetworkTracking } from "@/components/networkTracking";
import { Navbar } from "@/components/navbar";

import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout component.
 *
 * This component is the top-level layout component that wraps all pages.
 * It renders the navbar and the children (i.e. the current page).
 */
export default function RootLayout({ children }) {
  return (
    /**
     * The ClerkProvider component is a wrapper around the Next.js app
     * that handles authentication and authorization.
     *
     * It injects the Clerk client into the context of the app, which
     * allows us to use the Clerk hooks and components.
     */
    <ClerkProvider>
      <html className="h-full" lang="en">
        <body className={`antialiased h-full`}>
          {/* The navbar component renders the navigation bar at the top of the page */}
          <Navbar />
          {/* The children prop is the current page */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
